### ISSUE TITLE
zeroize: Why does `DefaultIsZeroes` require `Copy`?

### ISSUE THREAD

**Issue by dvdplm** [RustCrypto/utils#1099]
Perhaps a dumb question, but it's not obvious to me why [`DefaultIsZeroes`](https://github.com/RustCrypto/utils/blob/master/zeroize/src/lib.rs#L282) requires the type to be `Copy`? If it has to be that way, perhaps the motivation can be added to the docs?

**Comment by tarcieri** [comment]
`DefaultIsZeroes` is pretty much the foundational trait of `zeroize`, used as part of this blanket impl:

https://github.com/RustCrypto/utils/blob/c68a520/zeroize/src/lib.rs#L297-L305

```rust
impl<Z> Zeroize for Z
where
    Z: DefaultIsZeroes,
{
    fn zeroize(&mut self) {
        volatile_write(self, Z::default());
        atomic_fence();
    }
}
```

Note that's using an unsafe volatile pointer write to replace the original value with the `Default` value.

`Copy` highly constrains the types used by this operation to ones we're sure are safe to use in this capacity. We know there's no `Drop` handler that will be bypassed by this, for example (and `!Drop` is otherwise not stable to write as a bound).
