### ISSUE TITLE
Remove byteorder-dependency

### ISSUE THREAD

**Issue by lukaslueg** [RustCrypto/utils#29]
The `byteorder`-crate is not strictly needed since 1.32 and gets pulled in _a lot_ due to RustCrypto. Is there interest in removing it, raising the minimum Rust version to 1.32 in the process?

**Comment by newpavlov** [comment]
We definitely plan to bump MSRV to 1.32 in future versions of the crates, but I doubt it will significantly reduce usage of `byteorder`. Many transformations are between arrays or slices (e.g. [converting](https://github.com/RustCrypto/hashes/blob/master/sha2/src/sha256_utils.rs#L264) `[u8; 64]` to `[u32; 8]`) and standard library does not help us much here, since right now we don't have a way to slice an array without unsafe code.

Either way `byteroder` is a very common dependency and it makes code smaller, easier to read and understand, so I don't see why we should remove it completely.
