### ISSUE TITLE
Missing sodium_add and sodium_increment functions

### ISSUE THREAD

**Issue by kurnevsky** [RustCrypto/utils#390]
Currently there is no analogs of functions `sodium_add` and `sodium_increment` in rust crypto. Also would be good to have support for both variants that treat nonces as big endian and little endian numbers. For instance in tox we [have a revese](https://github.com/tox-rs/tox/blob/master/tox_crypto/src/lib.rs#L126) because libsodium supports only little endian option.

**Comment by tarcieri** [comment]
It sounds like you're asking for something that provides generic bignum functionality.

As it were, that's something I'd like to work on soon, although it may be awhile before we have something ready to use.

**Comment by newpavlov** [comment]
Going to close this issue. [`crypto-bigint`](https://github.com/RustCrypto/utils/tree/master/crypto-bigint) already implements addition, subtraction and (de)serialization, so I think it should cover use-cases of `sodium_add` and `sodium_increment`, albeit with a slightly more boilerplate.

**Comment by kurnevsky** [comment]
Just compared performance of `crypto-bigint` and classic implementation of constant time addition, and `crypto-bigint` was way slower (~10ns vs 150ns): https://github.com/tox-rs/tox/commit/2395a91f9656c52537b78ee62678bdd20f13e611

**Comment by tarcieri** [comment]
The core addition operation in `crypto-bigint` uses an [`adc`](https://x86.puri.sm/html/file_module_x86_id_4.html) instruction per-limb. It shouldn't be a source of performance issues unless some optimization issue is preventing LLVM from lowering it to `adc`.

In your code example, you're decoding an integer from big-endian bytes, performing addition, and then re-encoding it for every operation. The bottleneck there is almost certainly the decoding/encoding performance.

At the very least you should cache the intermediate `U192` so you're not reconstructing it from bytes every time. But also this isn't really a great use case for `crypto-bigint`, since you're dealing with values that from a practical perspective do not need a big integer.

**Comment by kurnevsky** [comment]
> The bottleneck there is almost certainly the decoding/encoding performance.

Yeah, of course. But it's a common case that users might need to increment nonce, and currently they can't do this without at least decoding from bigint types. So it might be useful to have such plain functions that work with nonces. Though in tox we have quite unusual case where we need to add arbitrary u16 to a nonce in a big endian format.

> At the very least you should cache the intermediate U192 so you're not reconstructing it from bytes every time.

Right, but still we will have to convert it to nonce after each increment, so it won't be much faster.

> You almost certainly don't need to represent the full range of values from 0 to 6277101735386680763835789423207666416102355444464034512896 for what I am guessing is the purposes of a nonce which is incremented once per AEAD message.

Didn't really get your point here. In tox we generate arbitrary nonce and then increment it, so it can easily have any values from this range. But it doesn't really change anything.

Overall it wasn't a complain, just a note. I'm fine leaving our current implementation for now - it's quite simple and obvious.
