### ISSUE TITLE
Use ref in hex macro

### ISSUE THREAD

**Issue by Slals** [RustCrypto/utils#41]
Hello,

Is there a work arround to use ref instead of string literal in `hex!`?

```
let key = String::from("ff00ff00ff00ff00ff00");
hex!(key.as_str()); // expected one string literal
```

Does this macro should include format such as `println!("{}", key)`? If so I can make a PR but I'm not so sure.

Thanks

**Comment by newpavlov** [comment]
Unfortunately it's not possible. `hex!` macro has to expand at compile-time. For runtime transformation check out the [`hex`](https://docs.rs/hex/) crate.

**Comment by tarcieri** [comment]
Something interesting to consider now is a `const fn` equivalent

**Comment by newpavlov** [comment]
I am not sure it will be possible to do in the near future, since `const fn` will receive `&str` without any indication of length, so we will not be able to compute length of the output array. Jne thing which I am looking forward to is removal of the `proc-macro-hack` dependency, although it will result in bumping MSRV to the future stable.
