### ISSUE TITLE
Y2k still causing issues

### ISSUE THREAD

**Issue by ajpauwels** [RustCrypto/utils#568]
I'm amazed and honestly a little excited if I actually found a Y2k bug 21 years after the fact, but I can't seem to encode UtcTime values when the Duration specified during construction is a date after December 31st, 1999 at 23:59:59.

This works:

```rust
let test_time = UtcTime::new(std::time::Duration::from_secs(946684799u64)).unwrap();
let der_encoded_time = test_time.to_vec().unwrap();
```

This does not work:

```rust
let test_time = UtcTime::new(std::time::Duration::from_secs(946684800u64)).unwrap();
let der_encoded_time = test_time.to_vec().unwrap();
```

```
thread 'x509::tests::test_serialization' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Value { tag: Tag(0x17: UTCTime) }, position: None }', src/x509.rs:283:51
```

**Comment by tarcieri** [comment]
Fixed in #569.

Yes, this was a bug in the handing of 2-digit dates.

`UTCTime` uses a 2-digit date which RFC 5280 stipulates be interpreted as falling within the range 1950..=2049. Note that `der::UtcTime` uses UNIX timestamps internally and therefore doesn't support dates before 1970.

Though decoding of dates was properly tested, encoding was not, and the encoder failed when a date had a year > 1999.

I've now added much more extensive tests.

Note that because 2-digit years are problematic (as you've observed), modern applications should instead use `GeneralizedTime`, which uses a 4-digit year (isn't ASN.1 great?)

**Comment by ajpauwels** [comment]
Awesome thank you for the quick fix :) Did not know about GeneralizedTime.

**Comment by ssokolow** [comment]
> Note that `der::UtcTime` uses UNIX timestamps internally and therefore doesn't support dates before 1970.

Your conclusion does not automatically follow from your premise.

Linux represents UNIX timestamps as *signed* integers and I actually [had Serde panic](https://github.com/serde-rs/json/issues/464) (reported in 2018, still open) when trying to serialize some `mtime`s retrieved from an ext3 filesystem (some of them originating on a FAT12 floppy disk that had its file metadata set incorrectly) which were pre-1970. (Some being `-1` which could either be an off-by-one or a failure return that was mistaken for data and fed to the "set mtime" call, and some being what I can only assume was an application feeding corrupted memory to whatever DOS's "set modification time" call is.)

**Comment by tarcieri** [comment]
The current API is based on a `core::time::Duration` since the `UNIX_EPOCH`.

`Duration` is inherently signed.

**Comment by ssokolow** [comment]
> The current API is based on a `core::time::Duration` since the `UNIX_EPOCH`.
> 
> `Duration` is inherently signed.

Ahh, so the same mistake Serde made then? Not accounting for the `-1` = `SystemTimeError(Duration { secs: 1, nanos: 0 })` case?

**Comment by tarcieri** [comment]
If you think there is a potential footgun in the API, please post a PoC.

**Comment by ssokolow** [comment]
I was referring to how dealing with negative UNIX timestamps *in Rust* is a bit footgun-y because of how parts like `SystemTime` work. Sorry for side-tracking there.

My original point was just as I said. That actual Unixoid OSes are a real-world counter-example to the "and therefore" part of "uses UNIX timestamps internally and therefore doesn't support dates before 1970".

**Comment by tarcieri** [comment]
Note that use of `SystemTime` is minimized and optional so this crate can support its full feature set in `no_std` environments.

Again, if you can spot a problem there, please post a PoC.

**Comment by ssokolow** [comment]
Understood.

**Comment by masklinn** [comment]
> Linux represents UNIX timestamps as _signed_ integers 

Yeah but that’s really not portable behaviour across software, so rejecting dates before the epoch might be the safer pick. 

Notably, I discovered that Git uses unsigned 32b integers internally, however the behaviour of commit dates is basically unspecified so there’s no guarantee other frontends will behave the same (on input or output).

**Comment by ssokolow** [comment]
True. It's really more a question of where in the stack it's appropriate to apply what behaviour.

It was a *huge* footgun I had to work around when Serde panicked several minutes into a batch job because it doesn't support pre-epoch `SystemTime` and I was trying to cache a big pile of `stat` calls.

Imagine if it had panicked in the middle of the night and I was a sysadmin. That's the sort of footgun Rust is supposed to minimize.

It's sort of the octal IP address parsing bug in reverse.
