### ISSUE TITLE
x509/pkcs8: clarifying relation between pkcs8::AlgorithmIdentifier struct and x509::AlgorithmIdentifier trait

### ISSUE THREAD

**Issue by ajpauwels** [RustCrypto/utils#574]
There's a couple inconsistencies here I'd be happy to resolve but would like a maintainer to tell me if these are acceptable solutions or if there's something I don't know about dev direction I should take into account:

- pkcs8::AlgorithmIdentifier is a struct that represents an X509 AlgorithmIdentifier, it contains an ObjectIdentifier and an optional params field
- x509::AlgorithmIdentifier is a trait that defines associated methods that retrieve an ObjectIdentifier (defined as an associated type that implements AsRef<[u64]>) and the params
- pkcs8::AlgorithmIdentifier does NOT implement x509::AlgorithmIdentifier
- pkcs8::AlgorithmIdentifier DOES allow for retrieval of a slice of integers that represent the object identifier, however these are defined as u32 while the trait specifies a slice of u64
- when using x509::write::{certificate, tbs_certificate}, the parameters which require an AlgorithmIdentifier take a generic x509::AlgorithmIdentifier and therefore the primitives defined in pkcs8 cannot be used

My questions are:
1. Is the disconnect between pkcs8 and x509 intentional or something we should aim to resolve?
2. Would a PR implementing x509::AlgorithmIdentifier on pkcs8::AlgorithmIdentifier be welcome?
3. Should an ObjectIdentifier be a slice of u64 or u32?

Thank you for your time!

**Comment by tarcieri** [comment]
When you talk about an `AlgorithmIdentifier`, I assume you're referring to this:

https://docs.rs/x509/0.2.0/x509/trait.AlgorithmIdentifier.html

To clarify part of your confusion, there are currently "two" `x509` crates:

- @str4d's `x509` crate, currently published on crates.io: https://github.com/str4d/x509.rs
- The one located at https://github.com/RustCrypto/utils/tree/master/x509

As a bit of history, I gave @str4d the `x509` crate name as a means-to-an-end in completing the `yubikey` crate we collaborated on. However, he sounded okay with giving it back if we can reach feature parity with his current implementation, as he has plenty of other projects and isn't terribly excited about maintaining a full-featured X.509 library in perpetuity.

> Is the disconnect between pkcs8 and x509 intentional or something we should aim to resolve?

Within the crates in this repo, `AlgorithmIdentifier` is defined in the `spki` crate, which is consumed by `pkcs5`, `pkcs8`, and `x509`:

https://docs.rs/spki/0.4.0/spki/struct.AlgorithmIdentifier.html

> Would a PR implementing x509::AlgorithmIdentifier on pkcs8::AlgorithmIdentifier be welcome?

Hopefully I've already answered this question: the RustCrypto `x509` crate re-exports `spki::AlgorithmIdentifier`:

https://github.com/RustCrypto/utils/blob/d0746a87fe5adf041af44e06051d698525f738fc/x509/src/lib.rs#L27

> Should an ObjectIdentifier be a slice of u64 or u32?

Unfortunately X.660 places no bounds on the size of an integer associated with a particular OID arc, so this is a difficult question to answer. To my knowledge, `u32` is sufficient to model all OIDs used by the relevant PKIX, PKCS, and CMS standards.

Within the RustCrypto crate ecosystem, OIDs are modeled by the `const-oid` crate. Currently it uses `u32` arcs:

https://docs.rs/const-oid/0.6.0/const_oid/type.Arc.html

It does not, however, model arcs as a slice. Rather, it uses an iterator:

https://docs.rs/const-oid/0.6.0/const_oid/struct.Arcs.html

It does this because it internally models OIDs using their ASN.1 DER serialization (i.e. big endian base-128). It uses a fixed-width byte array which allows it to be const-friendly (presently you can't presently use heap-allocated data structures with `const fn`) and because all RustCrypto crates are designed to support "heapless" `no_std` environments.

If you are aware of any counterexamples from PKIX, PKCS, CMS, or other relevant cryptography standards which cannot be modeled by the `const-oid` crate, we can adjust the current constraints.

Additionally, imposing constraints should help prevent various runaway serialization/deserialization bugs. I suspect, but have not thoroughly evaluated, that bugs like this exist in the heap-backed `oid` crate, which does not apply any such constraints.

**Comment by ajpauwels** [comment]
Ok, things are looking much clearer now. Thank you for writing this up @tarcieri it helps tremendously.

It seems like my earlier issues were me mainly misunderstanding that the published x509 is not a rustcrypto project, and that AlgorithmIdentifier was a re-export of spki's. I'll simply use the spki::AlgorithmIdentifier struct, wrap it, and implement the currently published x509's trait on the wrapping type so I can use some of the functionality provided there.

Closing the issue as the relation has indeed been clarified.
