### ISSUE TITLE
Zeroizing: mutable mandatory or optional?

### ISSUE THREAD

**Issue by Ontokrat** [RustCrypto/utils#686]
Just a question:

- Does the wrapper `Zeroizing::new()` applied to a variable needs this variable to be mutable?
- And if not, can we be sure that the variable is effectively rewrote?

```rust
let mut alice = Zeroizing::new("alice".to_string()); // variable does not need to be mutable

let bob = Zeroizing::new("bob".to_string());
bob.zeroize(); //cannot borrow `bob` as mutable, as it is not declared as mutable
```
`alice` without `mut` compiles without warning and runs fine.

The [doc says](https://docs.rs/zeroize/1.4.3/zeroize/#zeroizingz-wrapper-for-zeroizing-arbitrary-values-on-drop):
>Zeroizing<Z: Zeroize> [..] also impls a Drop handler which calls zeroize() on its contents:

As `zeroize()` do need the variable to be mutable (well to re-write it), I'm a bit lost.
Thanks.

**Comment by tarcieri** [comment]
The signature of `Drop` is:

```rust
pub trait Drop {
    fn drop(&mut self);
}
```

This is possible since `Drop` only occurs when all other references have gone out of scope, i.e. the lifetime of the value is over. Thus a drop handler is able to obtain mutable access to a value even if all of the other references to the value in the program are immutable-only.
