### ISSUE TITLE
Should `zeroize::DefaultIsZeroes` be a sealed trait?

### ISSUE THREAD

**Issue by anp** [RustCrypto/utils#747]
It looks like the trait is only implemented for a few types within zeroize itself, but it's public and can be implemented by any user.

Which means (however weird the code is), I think you'd be able to implement `DefaultIsZeroes` for a `Copy` type that also had a non-trivial `Drop` impl, and then have that impl "leaked" by the `volatile_write` in the `impl<Z: DefaultIsZeroes> Zeroize for Z`.

Would it make sense to seal the trait so that only the known primitive types have that Zeroize impl provided?

**Comment by tarcieri** [comment]
We make extensive use of `DefaultIsZeroes` within the @RustCrypto ecosystem.

Here are some example usages in our elliptic curve crates. Note that all of these types are `Copy` and fall into the "values may or may not contain secrets" category:

https://github.com/RustCrypto/elliptic-curves/search?q=defaultiszeroes

I just opened a PR to the `num-bigint-dig` crate, used by the `rsa` crate, to use it:

https://github.com/dignifiedquire/num-bigint/pull/39

That particular PR is illustrative of its utility: it provides the simplest and cleanest path to implementing `Zeroize` for any type so long as that type can impl `Default`. These are otherwise cases where there aren't otherwise ways to compose a `Zeroize` impl from what the crate provides.

`DefaultIsZeroes` winds up being the bedrock on which all `Zeroize` impls are based, and that's functionality that's useful to all consumers of the crate, not just internally.

> Which means (however weird the code is), I think you'd be able to implement `DefaultIsZeroes` for a `Copy` type that also had a non-trivial `Drop` impl

`Copy` and `Drop` are orthogonal. You cannot implement `Drop` for a `Copy` type. The language does not allow it.

Backing up to an example, in the `elliptic-curve` crate we have a `SecretKey` type which does zeroize-on-drop. It's a newtype for a `Scalar`, which is a `Copy` type that impls `DefaultIsZeroes`. So the way we'd recommend you combine these things is an inner `Copy` type that may-or-may-not contain secrets, and an outer zeroize-on-drop type which is intended specifically for secret storage.

All of that said, `zeroize` is a post-1.0 crate with a trait-heavy API, so it's not really possible to make many major changes like this at this point short of using deprecations.
