### ISSUE TITLE
cpufeatures: add XGETBV checks

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/utils#793]
According to the [Intel manual](https://www.intel.com/content/dam/develop/external/us/en/documents/36945), when detecting features like AVX and AVX2 we should first check availability of the XGETBV instruction and then check that OS supports XMM and YMM registers.

**Comment by gabrielesvelto** [comment]
The link in the first comment is dead but the document has [been archived](https://web.archive.org/web/20220709041756/https://www.intel.com/content/dam/develop/external/us/en/documents/36945) fortunately. We're hitting a crash in Firefox because of this, see bug [1838108](https://bugzilla.mozilla.org/show_bug.cgi?id=1838108).

The full detection sequence for AVX from the Intel manual is the following:
1) Detect CPUID.1:ECX.OSXSAVE[bit 27] = 1 (XGETBV enabled for application use).
2) Issue XGETBV and verify that XFEATURE_ENABLED_MASK[2:1] = ‘11b’ (XMM state and YMM state are enabled by OS).
3) detect CPUID.1:ECX.AVX[bit 28] = 1 (AVX instructions supported).

From what I can tell what the crate is missing at the moment is step 2.

**Comment by tarcieri** [comment]
It seems like we can use [`core::arch::x86_64::_xgetbv`](https://doc.rust-lang.org/nightly/core/arch/x86_64/fn._xgetbv.html).

Something like this? (after detecting XGETBV is enabled)

```rust
let xcr0 = unsafe { core::arch::x86_64::_xgetbv(0) };

// XMM state and YMM state are enabled by OS
(xcr0 & 6) == 6
```

**Comment by tarcieri** [comment]
@newpavlov I guess that'd be all of the AVX-512 instructions? (and wouldn't it be XMM, YMM, and ZMM?)

**Comment by newpavlov** [comment]
I mean, shouldn't we technically check OS support for XMM registers when we use SSE instructions? Same for ZMM registers which are indeed used by AVX-512 instructions. After a cursory search I couldn't find information about them.

**Comment by tarcieri** [comment]
That seems like the safest option, although I'm curious what the Intel manual says

**Comment by ericlagergren** [comment]
> I mean, shouldn't we technically check OS support for XMM registers when we use SSE instructions? Same for ZMM registers which are indeed used by AVX-512 instructions. After a cursory search I couldn't find information about them.

I /believe/ you only need to check OSXSAVE for VEX-prefixed instructions.
