### ISSUE TITLE
block-padding does not support dynamic block sizes

### ISSUE THREAD

**Issue by czinn** [RustCrypto/utils#860]
It used to support this, but now that it uses BlockSize/Block, it’s no longer possible to set the block size dynamically. I don’t think the added safety of requiring the block size to be specified at compile time outweigh the costs of reduced functionality.

See https://stackoverflow.com/questions/75834956/is-it-possible-to-use-a-dynamic-block-size-with-block-padding for some additional context.

**Comment by newpavlov** [comment]
In general, we prefer to encode requirements in the type system and do things statically instead of dynamically. Knowing block size at compile time helps compiler to generate better code. Also `block-padding` is a building block used in higher level crates in this organization and it fits better with them this way.

What kind of application you writing which requires padding with variable block sizes?

**Comment by czinn** [comment]
Rabin’s information dispersal algorithm encodes bytes in blocks of size K where K is the threshold number of shares required to reconstruct the original data.

Would you be open to having two traits, one which looks like the current trait, and another which looks like the older trait? The former can be defined in terms of the latter, and users who need the additional functionality can bypass the static size requirement.

**Comment by newpavlov** [comment]
I guess it should be fine to have an additional dynamic trait? Though we may need to be careful with code reuse. We should verify that it does not degrade code generation for the static trait.

**Comment by czinn** [comment]
Cool, I’ll write a pull request. I’m a bit skeptical that the static block size results in better code generation here, but in any case I think inclining should prevent any degradation there.
