### ISSUE TITLE
hybrid-array: is the `ByteArray` type alias useful?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/utils#987]
`hybrid-array` currently contains a [`ByteArray`](https://docs.rs/hybrid-array/0.2.0-pre.5/hybrid_array/type.ByteArray.html) type alias which maps to `Array<u8, U>`.

I'm wondering if it's actually useful or perhaps less clear than just using `Array<u8, U>`.

It's been used in a few places in the WIP `crypto-common`/`block-buffer`/`cipher`/`digest` prereleases.

**Comment by newpavlov** [comment]
Personally, I prefer `Array<u8, U>`, but I am fine with `ByteArray<U>`.

They both have exactly the same length and the latter is slightly easier to type and read, but it could be slightly confusing since Rust often substitutes type aliases, e.g. compilation error messages will contain `Array<u8, U>`, despite code seemingly only using `ByteArray<U>`.
